### ISSUE TITLE
About the smart revise bot:

### ISSUE THREAD

**Issue by Pixel1011** [Dinoosawruss/Dinoosawruss#2]
I did actually find a way to bypass their checks but you probably dont want to fix the bot anymore but i was just pretty happy to find the way to do it so im just leaving this here to let you know, but anyway good luck on future projects you might do :)

**Comment by Dinoosawruss** [comment]
I'll happily discuss it on discord out of interest

Feel free to add me @Dinoosawruss#5358 

I think it is best to respect their wishes though
